version: 2
mergeable:
  # - when: schedule.repository
    # validate:
      # - do: stale
        # days: 20
        # type: pull_request
    # pass:
      # - do: comment
        # payload:
          # body: This is old. Is it still relevant? Consider closing or updating the pull request.
  - when: pull_request.*, pull_request_review.*
    validate:
      - do: title
        # Enforce semantic release convention.
        must_include:
          regex: ^((?<!([A-Za-z]{1,10})-?)[A-Z]+-\d+:)
          message: Title must include a properly formatted Jira issue number with a colon directly following the issue number.
        must_exclude:
          regex: ^\[WIP\]
      - do: description
        # All todo check boxes must be checked.
        must_exclude:
          regex: \[ \]
          message: There are incomplete TODO task(s) unchecked.
        no_empty:
          enabled: true
          message: Descriptions matter and should not be empty. Provide detail with **what** was changed, **why** it was changed, and **how** it was changed.

      # - do: size
        # No overly large PRs
        # ignore:
        # lines:
          # max:
            # count: 500
            # message: Change is very large, Should be under 500 lines of additions and deletions.
      # - do: approvals
        # Require approvers
        # min:
          # count: 1

    pass:
      - do: merge
        merge_method: 'squash'
      - do: checks
        status: 'success'
